### ISSUE TITLE
[meta] Unexpected occasions

### ISSUE THREAD

**Issue by Riajyuu** [FoxAuth/FoxAuth#32]
Lacking of vector images:
- [ ] totheglory.im
- [ ] thetechgame.com
- [x] localbitcoins.com
- [ ] cloudns.net
- [ ] directnic.com
- [ ] easydns.com
- [ ] internetbs.net
- [ ] joker.com
- [ ] register4less.com
- [ ] clever.com
- [ ] mail.de
- [ ] pobox.com
- [ ] startmail.com
- [ ] pocketsmith.com
- [ ] followmyhealth.com
- [ ] nimbox.co.uk
- [ ] fortrabbit.com

Test account required as we can't complete it ourselves since we don't have necessary info (e.g. SSN code, credit cards, website locale unrecognized, etc.):
- [ ] dreamhost.com
- [ ] transip.nl
- [ ] speedit.org
- [ ] braintreegateway.com
- [ ] rackspace.com
- [ ] upcloud.com
- [ ] cm.com
- [ ] compose.com

new autofill logic required:
- [ ] stackpath.com (CC @brucehuanglove , this one simply needs hacking like Atlassian)
- [ ] nearlyfreespeech.net, tinfoilsecurity.com (three lines of input)
